# Generated by Django 3.2.7 on 2021-09-28 18:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid5,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                (
                    'function',
                    models.IntegerField(
                        choices=[
                            (1, 'Harvest'),
                            (2, 'Pruning'),
                            (3, 'Scouting'),
                            (4, 'Other'),
                        ]
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
