# Generated by Django 4.0a1 on 2021-09-28 21:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                (
                    'function',
                    models.CharField(
                        max_length=255,
                        choices=[
                            ('Harvest', 'Harvest'),
                            ('Pruning', 'Pruning'),
                            ('Scouting', 'Scouting'),
                            ('Other', 'Other'),
                        ],
                        default='Other',
                    ),
                ),
            ],
            options={
                'db_table': 'workers',
                'ordering': ['id'],
            },
        ),
    ]
