# Generated by Django 3.2.7 on 2021-09-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_worker_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='function',
            field=models.TextField(
                choices=[
                    ('Harvest', 'Harvest'),
                    ('Pruning', 'Pruning'),
                    ('Scouting', 'Scouting'),
                    ('Other', 'Other'),
                ]
            ),
        ),
    ]
