# Generated by Django 3.2.7 on 2021-09-28 18:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_worker_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='id',
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
