# Generated by Django 3.2.7 on 2021-09-28 18:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_worker_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='id',
            field=models.UUIDField(
                default=uuid.uuid5, primary_key=True, serialize=False
            ),
        ),
    ]
